[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_url = "https://base-mainnet.g.alchemy.com/v2/k3Dvibh6qSOCk1KkssKyZub9r6AuK1qy"
block_number = 26558775

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# anvil --fork-url https://base-mainnet.g.alchemy.com/v2/k3Dvibh6qSOCk1KkssKyZub9r6AuK1qy --fork-block-number 26558775